spring:
  application:
    name: MySpringBoot2Dbase
  datasource:
    url: jdbc:h2:/Users/melni/IdeaProjects/java-core_2024-2025/MySpringBoot2Base/testdb/students
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

server:
  port: 8082




